### ISSUE TITLE
version 3.02

### ISSUE THREAD

**Issue by SuigetsuShinso** [CalcProgrammer1/KeyboardVisualizerVCUI_Release#3]
Razer Blackwidow Chroma v2, entire keyboard remains black, but my Razer Naga Chroma works with this release just fine. Sometimes, the keyboard will remain in it's default state and ignore the Keyboard Visualizer entirely.

**Comment by CalcProgrammer1** [comment]
BWC v2 just came out and I don't know if they updated the SDK to add a device ID for it yet.  You can try adding razer_use_keyboard_generic_effect to your settings to use the generic effect instead of per device effects.

**Comment by SuigetsuShinso** [comment]
That currently works. Thanks.
